### ISSUE TITLE
raspi+docker環境でdockerコンテナの起動に失敗してしまいました

### ISSUE THREAD

**Issue by seigot** [Tiryoh/docker_ros-desktop-vnc#10]
raspi+docker環境でdockerコンテナの起動に失敗してしまいました
raspberrypi4+raspbian busterです。docker run時に以下のエラーが出てしまいました。
これは何か設定が足りないのでしょうか。もし何か知見をお持ちでしたら指摘頂けると助かります。

```
pi@raspberrypi:~ $ sudo docker run -p 6080:80 --shm-size=512m tiryoh/ros-desktop-vnc:melodic
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by Tiryoh** [comment]
@seigot [tiryoh/ros-desktop-vnc](https://github.com/Tiryoh/docker_ros-desktop-vnc)がベースとしているDockerイメージ（[dorowu/ubuntu-desktop-lxde-vnc](https://github.com/fcwu/docker-ubuntu-vnc-desktop)）は[`amd64`用だけ公開されています](https://hub.docker.com/r/dorowu/ubuntu-desktop-lxde-vnc/tags)。そのためArmのCPUを搭載したRaspberry Pi上ではそのままでは使用できません。

https://github.com/fcwu/docker-ubuntu-vnc-desktop
上記のリポジトリ内には`arm64`用Dockerfileも公開されているようですので、以下の手順を踏むともしかしたらros-desktop-vncをRaspberry Pi 4上で動かすことができるかもしれません。

1. [dorowu/ubuntu-desktop-lxde-vnc](https://github.com/fcwu/docker-ubuntu-vnc-desktop)をRaspberry Pi 4上でビルド
2. [tiryoh/ros-desktop-vnc](https://github.com/Tiryoh/docker_ros-desktop-vnc)をRaspberry Pi 4上でビルド

**Comment by seigot** [comment]
ご回答ありがとうございます。
上記、試してみようと思います。

**Comment by seigot** [comment]
以下の通り、arm64向けのdorowu/ubuntu-desktop-lxde-vncを取得してDockerのFROMに指定してビルドすると起動できました。

```
sudo docker pull dorowu/ubuntu-desktop-lxde-vnc:bionic-arm64
```

アドバイスありがとうございました。
